### ISSUE TITLE
Throw errors for missing dependencies

### ISSUE THREAD

**Issue by jflory7** [unicef/magicbox-aggregate-mobility#12]
# Summary

Throw an error to user if a required dependency is missing from the project

# Analysis

I ran the project a few times and it seemed to finish successfully. However, it did not generate any results and did not run most of the code because I was missing `spark-shell`. The program should throw an error when a dependency is missing, so the user understands that it did not execute successfully, and also how to fix the error.

# Expected results

```
$ node main.js 
Error: spark-shell missing. Please make sure spark-shell is in your PATH.
```

…or…

```
$ node main.js 
Error: Hadoop version too old. Please use vX.X.X or later.
```

# Actual results

```
$ node main.js 
end read traffic_weeks_definitions
Done with all!!!
```

**Comment by joyrex2001** [comment]
Instead of version checking, I added some error handling in main.js which will (if https://github.com/unicef/magicbox-aggregate-mobility/pull/33 is merged as well), exit with an error. See pull request https://github.com/unicef/magicbox-aggregate-mobility/pull/34

**Comment by thoat** [comment]
I know at least on my machine, with @joyrex2001 's PR, the code now throws exit status with an error number, so this issue is more or less resolved. (Sorry didn't screenshot it before installing the necessary packages, so I can't show a proof here).

**Comment by justwheel** [comment]
@thoat Thanks for following up and confirming it was fixed! Thanks @joyrex2001 for making the contribution. I'll close this issue out.
