### ISSUE TITLE
travis build broken (but says it's passing)

### ISSUE THREAD

**Issue by JoachimC** [unicef/magicbox-aggregate-mobility#30]
https://travis-ci.org/unicef/magicbox-aggregate-mobility/builds

Expected:
* travis build shows failure when tests aren't run
* travis runs tests and test outcome is reflected in the build result

Actual: 
* build history shows green for some builds but the log for each actually shows an error thrown
* looks like it's having trouble finding the ```spark-shell``` binary

**Comment by jflory7** [comment]
I know we hard-linked a download file in the Dockerfile, and then the link went offline. If I saw correctly, #29 will close and fix this issue already, since it changes the link.

**Comment by JoachimC** [comment]
Yeah there’s a bit of overlap between this and #29. But this means either can be merged (or not) in any order.
